Fix bug: org.apache.catalina.LifecycleException: A child container failed during start, java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName(), caused by: the old tomcat-embed-core.jar, resolve: update Spring Boot version